services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    command: postgres -c log_statement=all
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'" ]
      timeout: 60s
      interval: 5s
      retries: 5
      start_period: 10s

  postgres_migrations:
    build:
      target: runtime
    environment:
      CRYPKIT_POSTGRES_HOST: "postgres"
      CRYPKIT_POSTGRES_USERNAME: "${CRYPKIT_POSTGRES_USERNAME}"
      CRYPKIT_POSTGRES_PASSWORD: "${CRYPKIT_POSTGRES_PASSWORD}"
      CRYPKIT_POSTGRES_DATABASE_NAME: "${CRYPKIT_POSTGRES_DATABASE_NAME}"
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy
