services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    command: postgres -c log_statement=all
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'" ]
      timeout: 60s
      interval: 5s
      retries: 5
      start_period: 10s

  postgres_migrations:
    build:
      target: runtime
    environment:
      CRYPKIT_POSTGRES_HOST: "postgres"
      CRYPKIT_POSTGRES_USERNAME: "${CRYPKIT_POSTGRES_USERNAME}"
      CRYPKIT_POSTGRES_PASSWORD: "${CRYPKIT_POSTGRES_PASSWORD}"
      CRYPKIT_POSTGRES_DATABASE_NAME: "${CRYPKIT_POSTGRES_DATABASE_NAME}"
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 60s
      interval: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      target: runtime
    ports:
      - "8000:8000"
    environment:
      CRYPKIT_POSTGRES_HOST: "postgres"
      CRYPKIT_POSTGRES_USERNAME: "${CRYPKIT_POSTGRES_USERNAME}"
      CRYPKIT_POSTGRES_PASSWORD: "${CRYPKIT_POSTGRES_PASSWORD}"
      CRYPKIT_POSTGRES_DATABASE_NAME: "${CRYPKIT_POSTGRES_DATABASE_NAME}"
      CRYPKIT_REDIS_CACHE_EXPIRATION_SECONDS: "${CRYPKIT_REDIS_CACHE_EXPIRATION_SECONDS}"
      CRYPKIT_REDIS_HOST: "redis"
      CRYPKIT_COIN_GECKO_API_KEY: "${CRYPKIT_COIN_GECKO_API_KEY}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres_migrations:
        condition: service_completed_successfully
